### ISSUE TITLE
Unhundled exception when setting up 2FA

### ISSUE THREAD

**Issue by mmartinortiz** [nextcloud/twofactor_gateway#129]
**Two-Factor Gateway**: 0.9.0
**Nextcloud**: 14.0.2 RC1

I've followed the instructions of the [admin documentation](https://nextcloud-twofactor-gateway.readthedocs.io/en/latest/Admin%20Documentation/) for setting up the two-factor authentification using telegram. My Nextcloud server runs in a docker container, so I run the `occ` command with the following command:

```bash
docker exec nextcloud sudo -u abc /usr/bin/php -f /config/www/nextcloud/occ twofactorauth:gateway:configure telegram
```

It raises the following error:

```
The current PHP memory limit is below the recommended value of 512MB.
Using .
An unhandled exception has been thrown:
TypeError: Argument 1 passed to OCA\TwoFactorGateway\Service\Gateway\Telegram\GatewayConfig::setBotToken() must be of the type string, null given, called in /config/www/nextcloud/apps/twofactor_gateway/lib/Command/Configure.php on line 155 and defined in /config/www/nextcloud/apps/twofactor_gateway/lib/Service/Gateway/Telegram/GatewayConfig.php:54
Stack trace:
#0 /config/www/nextcloud/apps/twofactor_gateway/lib/Command/Configure.php(155): OCA\TwoFactorGateway\Service\Gateway\Telegram\GatewayConfig->setBotToken(NULL)
#1 /config/www/nextcloud/apps/twofactor_gateway/lib/Command/Configure.php(80): OCA\TwoFactorGateway\Command\Configure->configureTelegram(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /config/www/nextcloud/3rdparty/symfony/console/Command/Command.php(251): OCA\TwoFactorGateway\Command\Configure->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /config/www/nextcloud/3rdparty/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /config/www/nextcloud/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OCA\TwoFactorGateway\Command\Configure), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /config/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /config/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /config/www/nextcloud/console.php(96): OC\Console\Application->run()
#8 /config/www/nextcloud/occ(11): require_once('/config/www/nex...')
#9 {main}
```

Can I provide more useful information? I'm not sure how to proceed to getting 2FA working. (I did not try with other providers)

**Comment by ChristophWurst** [comment]
Did you enter a bot token when you were asked for it?

**Comment by mmartinortiz** [comment]
I was not asked for a token, I just got the exception after I run the command

**Comment by ChristophWurst** [comment]
That is unexpected. The telegram configure command definitely asks for a token: https://github.com/nextcloud/twofactor_gateway/blob/aa730883d763ab070c011ba505240d767fda5243/lib/Command/Configure.php#L157-L167

**Comment by mmartinortiz** [comment]
Interesting... the exception I get points to the line 150, and the function in the repository starts at line 157. I've checked both files (my local file and the one in the repo) and they are different. 

```php
<?php

declare(strict_types=1);

/**
 * @author Christoph Wurst <christoph@winzerhof-wurst.at>
 *
 * Nextcloud - Two-factor Gateway
 *
 * This code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License, version 3,
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

namespace OCA\TwoFactorGateway\Command;

use OCA\TwoFactorGateway\Service\Gateway\IGateway;
use OCA\TwoFactorGateway\Service\Gateway\Signal\Gateway as SignalGateway;
use OCA\TwoFactorGateway\Service\Gateway\Signal\GatewayConfig as SignalConfig;
use OCA\TwoFactorGateway\Service\Gateway\SMS\Gateway as SMSGateway;
use OCA\TwoFactorGateway\Service\Gateway\SMS\GatewayConfig as SMSConfig;
use OCA\TwoFactorGateway\Service\Gateway\SMS\Provider\PlaySMSConfig;
use OCA\TwoFactorGateway\Service\Gateway\SMS\Provider\WebSmsConfig;
use OCA\TwoFactorGateway\Service\Gateway\Telegram\Gateway as TelegramGateway;
use OCA\TwoFactorGateway\Service\Gateway\Telegram\GatewayConfig as TelegramConfig;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\Question;

class Configure extends Command {

        /** @var SignalGateway */
        private $signalGateway;

        /** @var SMSGateway */
        private $smsGateway;

        /** @var TelegramGateway */
        private $telegramGateway;

        public function __construct(SignalGateway $signalGateway,
                                                                SMSGateway $smsGateway,
                                                                TelegramGateway $telegramGateway) {
                parent::__construct('twofactorauth:gateway:configure');
                $this->signalGateway = $signalGateway;
                $this->smsGateway = $smsGateway;
                $this->telegramGateway = $telegramGateway;

                $this->addArgument(
                        'gateway',
                        InputArgument::REQUIRED,
                        'The identifier (e.g. phone number) of the recipient'
                );
        }

        protected function execute(InputInterface $input, OutputInterface $output) {
                $gatewayName = $input->getArgument('gateway');

                /** @var IGateway $gateway */
                $gateway = null;
                switch ($gatewayName) {
                        case 'signal':
                                $this->configureSignal($input, $output);
                                break;
                        case 'sms':
                                $this->configureSms($input, $output);
                                break;
                        case 'telegram':
                                $this->configureTelegram($input, $output);
                                break;
                        default:
                                $output->writeln("<error>Invalid gateway $gatewayName</error>");
                                return;
                }
        }

        private function configureSignal(InputInterface $input, OutputInterface $output) {
                $helper = $this->getHelper('question');
                $urlQuestion = new Question('Please enter the URL of the Signal gateway (leave blank to use default): ', 'http://localhost:5000');
                $url = $helper->ask($input, $output, $urlQuestion);
                $output->writeln("Using $url.");

                /** @var SignalConfig $config */
                $config = $this->signalGateway->getConfig();

                $config->setUrl($url);
        }

        private function configureSms(InputInterface $input, OutputInterface $output) {
                $helper = $this->getHelper('question');
                $providerQuestion = new Question('Please choose a SMS provider (websms, playsms): ', 'websms');
                $provider = $helper->ask($input, $output, $providerQuestion);

                /** @var SMSConfig $config */
                $config = $this->smsGateway->getConfig();
                switch ($provider) {
                        case 'websms':
                                $config->setProvider($provider);
                                /** @var WebSmsConfig $providerConfig */
                                $providerConfig = $config->getProvider()->getConfig();

                                $usernameQuestion = new Question('Please enter your websms.de username: ');
                                $username = $helper->ask($input, $output, $usernameQuestion);
                                $passwordQuestion = new Question('Please enter your websms.de password: ');
                                $password = $helper->ask($input, $output, $passwordQuestion);

                                $providerConfig->setUser($username);
                                $providerConfig->setPassword($password);

                                break;
                        case 'playsms':
                                $config->setProvider($provider);
                                /** @var PlaySMSConfig $providerConfig */
                                $providerConfig = $config->getProvider()->getConfig();

                                $urlQuestion = new Question('Please enter your PlaySMS URL: ');
                                $url = $helper->ask($input, $output, $urlQuestion);
                                $usernameQuestion = new Question('Please enter your PlaySMS username: ');
                                $username = $helper->ask($input, $output, $usernameQuestion);
                                $passwordQuestion = new Question('Please enter your PlaySMS password: ');
                                $password = $helper->ask($input, $output, $passwordQuestion);

                                $providerConfig->setUrl($url);
                                $providerConfig->setUser($username);
                                $providerConfig->setPassword($password);

                                break;
                        default:
                                $output->writeln("Invalid provider $provider");
                                break;
                }

        }

        private function configureTelegram(InputInterface $input, OutputInterface $output) {
                $helper = $this->getHelper('question');
                $tokenQuestion = new Question('Please enter your Telegram bot token: ');
                $token = $helper->ask($input, $output, $tokenQuestion);
                $output->writeln("Using $token.");

                /** @var TelegramConfig $config */
                $config = $this->telegramGateway->getConfig();

                $config->setBotToken($token);
        }

}
```

I've disabled, removed and download the application again. The file I get installed is the same that I had previously. The `appinfo/info.xml` file indicates that the version is 0.9.0, though.

```
<?xml version="1.0"?>
<info xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="https://apps.nextcloud.com/schema/apps/info.xsd">
        <id>twofactor_gateway</id>
        <name>Two-Factor Gateway</name>
        <summary>Two-factor gateway providers (SMS, Telegram, Signal)</summary>
        <description>A set of Nextcloud two-factor providers to send authentication codes via Signal, SMS and Telegram.</description>
        <version>0.9.0</version>
        <licence>agpl</licence>
        <author>Christoph Wurst</author>
        <namespace>TwoFactorGateway</namespace>
        <category>security</category>
        <website>https://github.com/nextcloud/twofactor_gateway</website>
        <bugs>https://github.com/nextcloud/twofactor_gateway/issues</bugs>
        <screenshot>https://raw.githubusercontent.com/ChristophWurst/twofactor_gateway/3f895bc997c1a3a38c9bae16ccae8bd499af864e/screenshots/settings.png</screenshot>
        <screenshot>https://raw.githubusercontent.com/ChristophWurst/twofactor_gateway/3f895bc997c1a3a38c9bae16ccae8bd499af864e/screenshots/challenge.png</screenshot>
        <dependencies>
                <php min-version="7.0" max-version="7.2"/>
                <nextcloud min-version="14" max-version="14"/>
        </dependencies>

        <two-factor-providers>
                <provider>OCA\TwoFactorGateway\Provider\SignalProvider</provider>
                <provider>OCA\TwoFactorGateway\Provider\SmsProvider</provider>
                <provider>OCA\TwoFactorGateway\Provider\TelegramProvider</provider>
        </two-factor-providers>
        <commands>
                <command>OCA\TwoFactorGateway\Command\Configure</command>
                <command>OCA\TwoFactorGateway\Command\Status</command>
                <command>OCA\TwoFactorGateway\Command\Test</command>
        </commands>
        <settings>
                <personal>OCA\TwoFactorGateway\Settings\PersonalSettings</personal>
        </settings>
</info>
```

How can I delete the applications cache? I want to make sure to force the the app to be downloaded again after I remove it.

**Comment by ChristophWurst** [comment]
> Interesting... the exception I get points to the line 150, and the function in the repository star

Of course, because the master branch has change since the last release. You should be at this specific version: https://github.com/nextcloud/twofactor_gateway/blob/a5a7d4047ef80f485b81725fbca09afa6de20ea2/lib/Command/Configure.php#L146-L156.

Please don't change any files. If you do so and your installation breaks, you're on your own. I suggest to restore a backup with the previous state.

> How can I delete the applications cache? I want to make sure to force the the app to be downloaded again after I remove it.

That functionality does not exist. You can try overwriting the app directory with the latest release tarball.

**Comment by mmartinortiz** [comment]
If the master branch contains a new development version I think it should have a different version number, like the 0.10.0 or just a 0.9.1-dev.

In any case, I've tried with `sms` and `signal`. In the case of signal I get a `Using a localhost:5000` what I guess means that the argument is accepted. If I use `sms` I get an exception:

```
TypeError: Argument 1 passed to OCA\TwoFactorGateway\Service\Gateway\SMS\Provider\WebSmsConfig::setUser() must be of the type string, null given, called in /config/www/nextcloud/apps/twofactor_gateway/lib/Command/Configure.php on line 118 and defined in /config/www/nextcloud/apps/twofactor_gateway/lib/Service/Gateway/SMS/Provider/WebSmsConfig.php:52```

If I use a wrong gateway, I get a proper error message:

```
Invalid gateway noway
``` 

Could the problem be originated by the class `Question`?

**Comment by ChristophWurst** [comment]
> If the master branch contains a new development version I think it should have a different version number, like the 0.10.0 or just a 0.9.1-dev.

No, because we need the version bumps to trigger database migrations. Of course we could use even numbers for releases and odd ones for dev versions, but that breaks semver, which I'm a big fan of.

May I ask you what terminal you're using? Sounds like yours is not interactive and thus the questions are not asked. This is weird tbh.
